// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// run_bama_mcmc
Rcpp::List run_bama_mcmc(arma::vec& Y, arma::vec& A, arma::mat& M, arma::mat& C, arma::vec& beta_m_init, arma::vec& alpha_a_init, double pi_m_init, double pi_a_init, int burnin, int ndraws);
RcppExport SEXP _bama_run_bama_mcmc(SEXP YSEXP, SEXP ASEXP, SEXP MSEXP, SEXP CSEXP, SEXP beta_m_initSEXP, SEXP alpha_a_initSEXP, SEXP pi_m_initSEXP, SEXP pi_a_initSEXP, SEXP burninSEXP, SEXP ndrawsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta_m_init(beta_m_initSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type alpha_a_init(alpha_a_initSEXP);
    Rcpp::traits::input_parameter< double >::type pi_m_init(pi_m_initSEXP);
    Rcpp::traits::input_parameter< double >::type pi_a_init(pi_a_initSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type ndraws(ndrawsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_bama_mcmc(Y, A, M, C, beta_m_init, alpha_a_init, pi_m_init, pi_a_init, burnin, ndraws));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bama_run_bama_mcmc", (DL_FUNC) &_bama_run_bama_mcmc, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_bama(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
