# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rand_bernoulli <- function(p) {
    .Call('_hdbm_rand_bernoulli', PACKAGE = 'hdbm', p)
}

rand_invgamma <- function(shape, scale) {
    .Call('_hdbm_rand_invgamma', PACKAGE = 'hdbm', shape, scale)
}

#' @export
#' @useDynLib hdbm
#' @importFrom Rcpp evalCpp
run_hdbm_mcmc <- function(Y, A, M, C1, C2, beta_m_init, alpha_a_init, pi_m_init, pi_a_init, burnin, nsamples) {
    .Call('_hdbm_run_hdbm_mcmc', PACKAGE = 'hdbm', Y, A, M, C1, C2, beta_m_init, alpha_a_init, pi_m_init, pi_a_init, burnin, nsamples)
}

