# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib bama
#' @importFrom Rcpp evalCpp
run_bama_mcmc <- function(Y, A, M, C, beta_m_init, alpha_a_init, pi_m_init, pi_a_init, burnin, ndraws) {
    .Call('_bama_run_bama_mcmc', PACKAGE = 'bama', Y, A, M, C, beta_m_init, alpha_a_init, pi_m_init, pi_a_init, burnin, ndraws)
}

